### ISSUE TITLE
Codec is None on some movies

### ISSUE THREAD

**Issue by FrancescoGrazioso** [AstraeLabs/VibraVid#108]
Downloading "Il dittatore" from StreamingCommunity i got the following exception

```
ERROR:root:Error parsing M3U8 content: 'NoneType' object has no attribute 'split'
[18:40:03] Cant find a list of audios                                                                               my_m3u8.py:551
           Cant find a list of audios                                                                               my_m3u8.py:562
           Find resolution: None                                                                                    my_m3u8.py:569
Traceback (most recent call last):
  File "/app/run.py", line 223, in <module>
    main()
  File "/app/run.py", line 212, in main
    run_function(main_film_series, CLOSE_CONSOLE)
  File "/app/run.py", line 186, in run_function
    func()
  File "/app/run.py", line 124, in main_film_series
    download_film(
  File "/app/Src/Api/film.py", line 59, in download_film
    obj_download.download_m3u8()
  File "/app/Src/Lib/FFmpeg/my_m3u8.py", line 921, in download_m3u8
    self.manage_playlist(m3u8_playlist_text)
  File "/app/Src/Lib/FFmpeg/my_m3u8.py", line 591, in manage_playlist
    console.log(f"[cyan]Find codecs: [red]({self.codec.video_codec_name};{self.codec.audio_codec_name})")
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'video_codec_name'
```

The error dosen't occur on every download but only on some. Maybe it's something related on the type of file updated on StreamingCommunity

**Comment by FrancescoGrazioso** [comment]
the problem is also thrown in the same file in this block of code

```
with open(file_list_path, 'w') as file_list:
    for ts_file in ts_files:
        #absolute_path = os.path.abspath(os.path.join(full_path, ts_file))
        relative_path = os.path.relpath(os.path.join(full_path, ts_file))
        file_list.write(f"file '{relative_path}'\n")

# Concatenate and save the files and return the path to the output filename
return concatenate_and_save(
    file_list_path=file_list_path,
    output_filename=out_file_name,
    v_codec=self.codec.video_codec_name,
    a_codec=self.codec.audio_codec_name,
    bandwidth=self.codec.bandwidth
)
```

**Comment by Arrowar** [comment]
The origin of codecs is there: https://github.com/Ghost6446/StreamingCommunity_api/blob/main/Src%2FLib%2FFFmpeg%2Futil%2Fparser.py#L193, maybe dont exist in m3u8.

**Comment by Arrowar** [comment]
https://github.com/Ghost6446/StreamingCommunity_api/commit/cc96066bc886787df27d9c7107ada3e426946b24, need other fix but for the moment dont break all.

**Comment by FrancescoGrazioso** [comment]
Still getting the error during the segment join

```
[20:57:16] Key use => b20782cbc32a7843e7691d55950c9a6a                                                            my_m3u8.py:471
[parser.py:265 -     parse_video_info() ] 2024-04-12 20:57:16,807 - ERROR - Error parsing video info: argument of type 'StreamInfo' is not iterable
           Cant find a list of audios                                                                             my_m3u8.py:551
           Cant find a list of audios                                                                             my_m3u8.py:562
           Find resolution: 720                                                                                   my_m3u8.py:569
           Download video segments.                                                                               my_m3u8.py:690
Download:  100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1,252/1,252  [ 0:02:32 < 0:00:00 , 11  segment/s ]
[20:59:49] Join segments: video                                                                                   my_m3u8.py:789
Traceback (most recent call last):
  File "/app/run.py", line 223, in <module>
    main()
  File "/app/run.py", line 212, in main
    run_function(main_film_series, CLOSE_CONSOLE)
  File "/app/run.py", line 186, in run_function
    func()
  File "/app/run.py", line 124, in main_film_series
    download_film(
  File "/app/Src/Api/film.py", line 59, in download_film
    obj_download.download_m3u8()
  File "/app/Src/Lib/FFmpeg/my_m3u8.py", line 946, in download_m3u8
    self.download_videos()
  File "/app/Src/Lib/FFmpeg/my_m3u8.py", line 795, in download_videos
    video_track_path = self.join_ts_files(
                       ^^^^^^^^^^^^^^^^^^^
  File "/app/Src/Lib/FFmpeg/my_m3u8.py", line 744, in join_ts_files
    v_codec=self.codec.video_codec_name,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'video_codec_name'
```

**Comment by Arrowar** [comment]
Fix
