### ISSUE TITLE
Error in ASCII representation

### ISSUE THREAD

**Issue by FrancescoGrazioso** [AstraeLabs/VibraVid#110]
While trying to download a TV serie's season (SKAM 6th season, using * to get all the episodes) i get the following error

```
Traceback (most recent call last):
  File "/app/Src/Lib/Unidecode/__init__.py", line 60, in _get_ascii_representation
    table = Cache[section]
            ~~~~~^^^^^^^^^
KeyError: 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/run.py", line 223, in <module>
    main()
  File "/app/run.py", line 212, in main
    run_function(main_film_series, CLOSE_CONSOLE)
  File "/app/run.py", line 186, in run_function
    func()
  File "/app/run.py", line 115, in main_film_series
    download_series(
  File "/app/Src/Api/series.py", line 210, in download_series
    donwload_episode(tv_name, list_season_select[0])
  File "/app/Src/Api/series.py", line 177, in donwload_episode
    donwload_video(tv_name, index_season_selected, i_episode)
  File "/app/Src/Api/series.py", line 118, in donwload_video
    mp4_name = remove_special_characters(f"{map_episode_title(tv_name,video_source.obj_episode_manager.episodes[index_episode_selected - 1],index_season_selected)}.mp4")
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/Src/Util/mapper.py", line 33, in map_episode_title
    return transliterate(map_episode_temp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/Src/Lib/Unidecode/__init__.py", line 145, in transliterate_expect_ascii
    return _transliterate(string, errors, replace_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/Src/Lib/Unidecode/__init__.py", line 100, in _transliterate
    ascii_char = _get_ascii_representation(char)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/Src/Lib/Unidecode/__init__.py", line 69, in _get_ascii_representation
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/app/Src/Lib/Unidecode/x020.py'
```

**Comment by Arrowar** [comment]
Ep number, or just the title and name of the ep ?

**Comment by FrancescoGrazioso** [comment]
just searched "Skam", selected "Skam Italia", selected 6th season and then * for all the episodes of the season, on the first episode it crashed

**Comment by Arrowar** [comment]
Fix
