### ISSUE TITLE
Can't download - error 404 and the crashes

### ISSUE THREAD

**Issue by kogan92** [AstraeLabs/VibraVid#117]
Download: back-to-black
[Video.py :216 -
get_content 1 2024-04-22 22:08:50,062 - ERROR - Error getting content: 404 Client Error: Not
Found for url: https://vixcloud. co/embed/?token=f152f9f421ccda14eaa5bdda43930e8e&title=Back+to+Black&referer=1&expires=1
719004129&b=1
Traceback (most recent call last):
File "run.py", line 223, in ‹module >
File "run.py"
, line 212, in main
File "run.py"
', line 186, in run_function
File "run.py"
, Line 124, in main_film_series
File "Src\Api\film.py", line 46, in download_film File "Src\Api\Class\Video.py", line 204, in get_content File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://vixcloud. co/embed/?token=f152f9f421ccda14eaa
5bdda43930e8e&title=Back+to+Black&referer=1&expires=1719004129&b=1
[15112] Failed to execute script 'run' due to unhandled exception!

**Comment by kogan92** [comment]
@
