### ISSUE TITLE
Openssl error.

### ISSUE THREAD

**Issue by AlexDLZ** [AstraeLabs/VibraVid#134]
C:\Users\user\Downloads\StreamingCommunity_api-main (1)>python run.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\run.py", line 22, in <module>
    from Src.Api.Streamingcommunity import main_film_series as streamingcommunity_film_serie
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Api\Streamingcommunity\__init__.py", line 15, in <module>
    from .film import download_film
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Api\Streamingcommunity\film.py", line 11, in <module>
    from Src.Lib.Hls.downloader import Downloader
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Lib\Hls\__init__.py", line 3, in <module>
    from .downloader import Downloader
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Lib\Hls\downloader.py", line 29, in <module>
    from ..M3U8 import (
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Lib\M3U8\__init__.py", line 3, in <module>
    from .decryption import M3U8_Decryption
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\Src\Lib\M3U8\decryption.py", line 74, in <module>
    openssl_available = subprocess.run(["openssl", "version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\Downloads\StreamingCommunity_api-main (1)\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2]
How to fix that? I have python 3.12.3

**Comment by Arrowar** [comment]
Ciao dovreesti avere installare pycryptodome o avere openssl installato.
