### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#150]
lo uso da tempo, ma ora con l'ultima versione mi da questo errore:

`Traceback (most recent call last):
  File "C:\Users\ludo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ludo\streamingcom\run.py", line 93, in <module>
    main()
  File "C:\Users\ludo\streamingcom\run.py", line 37, in main
    domain, site_version = Page.domain_version()
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ludo\streamingcom\Src\Api\page.py", line 15, in domain_version
    domain = req_repo.json()['domain']
             ^^^^^^^^^^^^^^^
  File "C:\Users\ludo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3)`

Grazie

**Comment by Lovi-0** [comment]
sito ?

**Comment by Arrowar** [comment]
Riprova ora.

**Comment by ludogemma** [comment]
non cambia stesso identico errore.

**Comment by ludogemma** [comment]
ho scaricato la versione che da quando fai python run.py 

e mi da questo errore pure questa:

`[20:20:58] Internet is available!                                                                             os.py:412

System Summary:
Traceback (most recent call last):
  File "C:\Users\ludo\Desktop\streamingcommunity\run.py", line 167, in <module>
    initialize()
  File "C:\Users\ludo\Desktop\streamingcommunity\run.py", line 104, in initialize
    get_system_summary()
  File "C:\Users\ludo\Desktop\streamingcommunity\Src\Util\os.py", line 446, in get_system_summary
    glibc_version = 'glibc ' + '.'.join(map(str, platform.libc_ver()[1]))
                                                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\platform.py", line 198, in libc_ver
    with open(executable, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\ludo\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe'`

**Comment by Arrowar** [comment]
Prova a disinstallare python dallo store e installare quello dal sito sul reamde e seleziona poi add to path.

**Comment by ludogemma** [comment]
ok ma quale versione? va bene anche l'ultima?

**Comment by Arrowar** [comment]
Si certo se non va installa la 3.11
