### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sermatty** [AstraeLabs/VibraVid#172]
i was downloading a film called Souleymane’s Story from mostraguarda, and got this error:

i'm using the program on a docker-compose container, on a qnap os with an arm processor.

```
Download:  Souleymane’s Story

Traceback (most recent call last):
  File "/app/run.py", line 191, in <module>
    main()
  File "/app/run.py", line 183, in main
    run_function(input_to_function[category])
  File "/app/run.py", line 42, in run_function
    func()
  File "/app/Src/Api/mostraguarda/__init__.py", line 30, in search
    download_film(movie_details)
  File "/app/Src/Api/mostraguarda/film.py", line 51, in download_film
    player_links = soup.find("ul", class_ = "_player-mirrors").find_all("li")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by Arrowar** [comment]
The site is down.
