### ISSUE TITLE
TypeError: HttpClient.__init__() missing 1 required positional argument: 'headers

### ISSUE THREAD

**Issue by Fast0n** [AstraeLabs/VibraVid#177]
`Traceback (most recent call last):
  File "/mnt/f/downloader/StreamingCommunity/run.py", line 190, in <module>
    main()
  File "/mnt/f/downloader/StreamingCommunity/run.py", line 182, in main
    run_function(input_to_function[category])
  File "/mnt/f/downloader/StreamingCommunity/run.py", line 41, in run_function
    func()
  File "/mnt/f/downloader/StreamingCommunity/Src/Api/streamingcommunity/__init__.py", line 36, in search
    download_series(select_title, domain, site_version)
  File "/mnt/f/downloader/StreamingCommunity/Src/Api/streamingcommunity/series.py", line 145, in download_series
    download_episode(select_title.slug, i_season, download_all=True)
  File "/mnt/f/downloader/StreamingCommunity/Src/Api/streamingcommunity/series.py", line 84, in download_episode
    download_video(tv_name, index_season_selected, i_episode)
  File "/mnt/f/downloader/StreamingCommunity/Src/Api/streamingcommunity/series.py", line 58, in download_video
    ).start()
      ^^^^^^^
  File "/mnt/f/downloader/StreamingCommunity/Src/Lib/Downloader/HLS/downloader.py", line 731, in start
    self._process_playlist()
  File "/mnt/f/downloader/StreamingCommunity/Src/Lib/Downloader/HLS/downloader.py", line 849, in _process_playlist
    self.content_downloader.download_subtitle(self.download_tracker.downloaded_subtitle)
  File "/mnt/f/downloader/StreamingCommunity/Src/Lib/Downloader/HLS/downloader.py", line 451, in download_subtitle
    f.write(HttpClient().get_content(m3u8_sub_parser.subtitle[-1]))
            ^^^^^^^^^^^^
TypeError: HttpClient.__init__() missing 1 required positional argument: 'headers'`

**Comment by Fast0n** [comment]
I temporarily solved it by adding a Try and Catch

![image](https://github.com/user-attachments/assets/2686506c-d187-4a2f-ae17-e0dde891be3b)

**Comment by Arrowar** [comment]
Yes, i solved it a week ago but i don't have already update the version:: https://github.com/Lovi-0/StreamingCommunity/commit/6566dd6b3d7be9f96a8bcbffd03f0826dd0feaaf

If you download the solution i think the problem will be solved
