### ISSUE TITLE
auto update .json ERROR

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#178]
ciao usando l'ultimo tuo script, quando arriva il suggerimento per aggiornare il json, mi da questo errore:

Suggestion: (Experimental)
New final URL: https://altadefinizione.my/
Do you want to auto update config.json - 'altadefinizione' with domain: my [y/n] (y): y
Return domain: my

Traceback (most recent call last):
  File "C:\Users\user\Desktop\StreamingCommunity-main\run.py", line 190, in <module>
    main()
  File "C:\Users\user\Desktop\StreamingCommunity-main\run.py", line 182, in main
    run_function(input_to_function[category])
  File "C:\Users\user\Desktop\StreamingCommunity-main\run.py", line 41, in run_function
    func()
  File "C:\Users\user\Desktop\StreamingCommunity-main\Src\Api\altadefinizione\__init__.py", line 24, in search
    len_database = title_search(string_to_search)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\StreamingCommunity-main\Src\Api\altadefinizione\site.py", line 38, in title_search
    response.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://altadefinizione.my/?story=gattopard&do=search&subaction=search&titleonly=3'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

**Comment by Arrowar** [comment]
Il sito è down o troppo lento.

**Comment by ludogemma** [comment]
ok ed invece la funzione che hai aggiunto per tornare indietro come si usa?

**Comment by Arrowar** [comment]
> ok ed invece la funzione che hai aggiunto per tornare indietro come si usa?

Per il momento è solo su streamingcomumity e funziona solo quando non trova la playlist, appena ho tempo la aggiunga anche su tutti gli altri siti.

**Comment by Arrowar** [comment]
Aggiunto a tutti i siti, per il momento altadefinizione non funziona.
