### ISSUE TITLE
Problema durante il download con ddlstreamitaly ecc.

### ISSUE THREAD

**Issue by andrea1999-wq** [AstraeLabs/VibraVid#188]
Ciao innanzitutto complimenti per il progetto. ho vari errori tra cui questo mentre provo con ddlstreamitaly
Traceback (most recent call last):
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 199, in <module>
    main()
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 191, in main
    run_function(input_to_function[category])
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 41, in run_function
    func()
  File "/home/andrea/streaming/StreamingCommunity-main/Src/Api/ddlstreamitaly/__init__.py", line 47, in search
    download_thread(select_title)
  File "/home/andrea/streaming/StreamingCommunity-main/Src/Api/ddlstreamitaly/series.py", line 89, in download_thread
    last_command = display_episodes_list()
TypeError: display_episodes_list() missing 1 required positional argument: 'obj_episode_manager'
-----------------------------------------------------------------------------
con guardaserie ho questo: 
Traceback (most recent call last):
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 199, in <module>
    main()
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 191, in main
    run_function(input_to_function[category])
  File "/home/andrea/streaming/StreamingCommunity-main/run.py", line 41, in run_function
    func()
  File "/home/andrea/streaming/StreamingCommunity-main/Src/Api/guardaserie/__init__.py", line 31, in search
    len_database = title_search(string_to_search)
  File "/home/andrea/streaming/StreamingCommunity-main/Src/Api/guardaserie/site.py", line 58, in title_search
    for serie_div in table_content.find_all('div', class_='mlnew'):
AttributeError: 'NoneType' object has no attribute 'find_all'

con s.community mi salta gli episodi.

OS: debian 11 su rasp pi 4.

**Comment by Arrowar** [comment]
Grazie per i complimenti, che serie, stagione ed episodi danno problemi ?

**Comment by andrea1999-wq** [comment]
0ut3r bank$ per esempio. 1 stagione 1 episodio per esempio

**Comment by Arrowar** [comment]
Ora dovrebbe andare tutto prova a verificare
