### ISSUE TITLE
Errore ffmpeg

### ISSUE THREAD

**Issue by spikeminoda86** [AstraeLabs/VibraVid#21]
Purtroppo ogni volta che provo a scaricare qualcosa, orriva alla fine e mi da questo messa, oppure esce fuori subito dopo l'invio.

Insert ep number or (*) to download all ep: : 1
Download ep: 1 => Episodio 1
Quality select => 360p

[13:35:09] Find: 490 ts file to download                                                                     m3u8.py:82
Download   0% ---------------------------------------------------------------- 0/490  [ 0:00:00 < -:--:-- , ? bytes/s ]
Traceback (most recent call last):
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 47, in <module>
    main()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 39, in main
    download_tv(db_title[index_select]['id'], db_title[index_select]['slug'], site_version, domain)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 154, in main_dw_tv
    dw_single_ep(tv_id, eps, index_ep_select, domain, token, tv_name, season_select)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 134, in dw_single_ep
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 242, in dw_m3u8
    downloader.join_ts_files()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 213, in join_ts_files
    ts_files.sort(key=extract_number)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 211, in extract_number
    return int(''.join(filter(str.isdigit, file_name)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by Arrowar** [comment]
Nome del film o serie che oggi provo ?

**Comment by spikeminoda86** [comment]
In realtà me lo fa con qualsiasi cosa, in questo caso si tratta di "camera cafè" 
( fa lo stesso con tutto il resto, al massimo arriva al 100% e poi crolla )

**Comment by spikeminoda86** [comment]
Movie select: C'era una volta a… Hollywood
Quality select => 720p


[13:42:08] Find: 2424 ts file to download                                                                    m3u8.py:82
Download 100% ------------------------------------------------------------  2.4/2.4 K [ 0:01:31 < 0:00:01 , 8 bytes/s ]
Traceback (most recent call last):
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 47, in <module>
    main()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 35, in main
    download_film(db_title[index_select]['id'], db_title[index_select]['slug'], domain)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Api\film.py", line 101, in main_dw_film
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 242, in dw_m3u8
    downloader.join_ts_files()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 213, in join_ts_files
    ts_files.sort(key=extract_number)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 211, in extract_number
    return int(''.join(filter(str.isdigit, file_name)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by Arrowar** [comment]
Oggi vedo di risolvere se riesco

**Comment by spikeminoda86** [comment]
ok resto in attesa

**Comment by Arrowar** [comment]
![1](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/497cc97e-0302-4801-bb3d-29feaf554aac)
![2](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/35b97916-25fb-4e6b-9ae7-cff6d2b14236)

Appena provato con "C'era una volta a… Hollywood" e "Camera Café" stagione 5 ep 16 e funziona, prova a installare l'ultima versione.

**Comment by spikeminoda86** [comment]
attualmente è installata l'ultima versione che hai reso disponibile dello script. Provato a scaricare stesso tuo episodio, ecco l'errore: 

Insert ep number or (*) to download all ep: : 16
Download ep: 16 => Episode 16
Quality select => 360p


[17:54:02] Find: 402 ts file to download                                                                     m3u8.py:82
Download   0% ---------------------------------------------------------------- 0/402  [ 0:00:00 < -:--:-- , ? bytes/s ]
Traceback (most recent call last):
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 47, in <module>
    main()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\run.py", line 39, in main
    download_tv(db_title[index_select]['id'], db_title[index_select]['slug'], site_version, domain)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 154, in main_dw_tv
    dw_single_ep(tv_id, eps, index_ep_select, domain, token, tv_name, season_select)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Api\tv.py", line 134, in dw_single_ep
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 242, in dw_m3u8
    downloader.join_ts_files()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 213, in join_ts_files
    ts_files.sort(key=extract_number)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api-main\Src\Util\m3u8.py", line 211, in extract_number
    return int(''.join(filter(str.isdigit, file_name)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by Arrowar** [comment]
provi a toglirer -main dal nome della cartella

**Comment by spikeminoda86** [comment]
Niente, medesimo errore. Ho un dubbio, io ho aggiunto ffmpeg nelle variabili di ambiente (path) ma se in dos faccio ffmpeg -version non lo trova. potrebbe essere questo o non c'entra?

**Comment by Arrowar** [comment]
Si vuol dire che non è stata correttamente aggiuta, infatti ora stavo implementando il controllo se ffmpeg era presente o meno

**Comment by spikeminoda86** [comment]
il problema è che più che aggiungere la cartella ffmpeg in c: copiare e incollarne l'indirizzo che nel mio caso è appunt c:ffmpeg. alla path non so cosa fare. quacosa sicuramente sbaglio a questo punto

**Comment by Arrowar** [comment]
Devi aggiungere ffmpeg\bin\ a path

**Comment by spikeminoda86** [comment]
E allora mi sa che scarico la versione errata, perchè la cartella bin all'interno di ffmpeg non è presente

**Comment by Arrowar** [comment]
mi sa di si

**Comment by spikeminoda86** [comment]
ti aggiorno ;)

**Comment by spikeminoda86** [comment]
NIente da fare, ffmpeg ora lo trova, ma mi da sempre lo stesso errore.

Movie select: Rambo
Quality select => 720p


[18:24:09] Find: 1399 ts file to download                                                                    m3u8.py:82
Download   0% ------------------------------------------------------------- 0.0/1.4 K [ 0:00:00 < -:--:-- , ? bytes/s ]
Traceback (most recent call last):
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\run.py", line 47, in <module>
    main()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\run.py", line 35, in main
    download_film(db_title[index_select]['id'], db_title[index_select]['slug'], domain)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\Src\Api\film.py", line 101, in main_dw_film
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\Src\Util\m3u8.py", line 242, in dw_m3u8
    downloader.join_ts_files()
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\Src\Util\m3u8.py", line 213, in join_ts_files
    ts_files.sort(key=extract_number)
  File "C:\Users\Valentino\Desktop\StreamingCommunity_api\Src\Util\m3u8.py", line 211, in extract_number
    return int(''.join(filter(str.isdigit, file_name)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10:

**Comment by spikeminoda86** [comment]
DOPO AVER RIAVVIATO IL PC, SEMBRA FUNZIONARE :)))))

**Comment by Arrowar** [comment]
Perfetto

**Comment by spikeminoda86** [comment]
posso consigliarti una cosa da aggiungere in futuro? Anzi due:
un check da parte dello script che ti dice eventualmente cosa manca e cosa non va
La possibilità di scaricare più titoli nello stesso momento.
Per il resto, sei grande, davvero complimenti per il tuo lavoro

**Comment by Arrowar** [comment]
Certo ci pensero, appena aggiunto quello per ffmpeg devo ancora controllare se funziona quanto non è presente ma lo farò.
Grazie
