### ISSUE TITLE
Mostraguarda AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Hat3** [AstraeLabs/VibraVid#211]
Mostraguarda

Download:  Warriors of Future

Traceback (most recent call last):
  File "/app/test_run.py", line 5, in <module>
    main()
  File "/app/StreamingCommunity/run.py", line 199, in main
    run_function(input_to_function[category])
  File "/app/StreamingCommunity/run.py", line 41, in run_function
    func()
  File "/app/StreamingCommunity/Api/Site/mostraguarda/__init__.py", line 42, in search
    download_film(movie_details)
  File "/app/StreamingCommunity/Api/Site/mostraguarda/film.py", line 63, in download_film
    player_links = soup.find("ul", class_ = "_player-mirrors").find_all("li")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by Arrowar** [comment]
Porto il fix con la prossima versione ma non c'è nei loro server
