### ISSUE TITLE
Error requiremets

### ISSUE THREAD

**Issue by RobbieDS** [AstraeLabs/VibraVid#22]
Traceback (most recent call last):
  File "C:\Users\RobbieDS\Downloads\Download\run.py", line 5, in <module>
    from Src.Api.film import main_dw_film as download_film
  File "C:\Users\RobbieDS\Downloads\Download\Src\Api\film.py", line 6, in <module>
    from Src.Util.FFmpeg.m3u8 import dw_m3u8
  File "C:\Users\RobbieDS\Downloads\Download\Src\Util\FFmpeg\m3u8.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
  File "C:\Users\RobbieDS\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\Users\RobbieDS\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\Users\RobbieDS\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Impossibile trovare la procedura specificata.

grazie mille

**Comment by RobbieDS** [comment]
penso di aver risolto il problema..
pip install cryptography==3.4.8
ho installato questa versione... 

il sistema mi avvisa di qualche incompatibilità perche è una vecchia versione... pero alla fin fine lo script funziona... mentre se reinstallo l'ultima versione, lo script non funziona piu...

**Comment by Arrowar** [comment]
Ok perfetto domani allora aggiorno la versione delle librerie
