### ISSUE TITLE
Error request 

### ISSUE THREAD

**Issue by UrloMythus** [AstraeLabs/VibraVid#23]
``` 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 405, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f1cb82c45d0>, 'Connection to sc-u7-01.scws-content.net timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 800, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sc-u7-01.scws-content.net', port=443): Max retries exceeded with url: /hls/180/9/da/9da93c0f-ba83-46e2-891e-5c1d2aa38016/audio/ita/0403-0100.ts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1cb82c45d0>, 'Connection to sc-u7-01.scws-content.net timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/urlo/Documenti/StreamingCommunity_api-main/run.py", line 62, in <module>
    main()
  File "/home/urlo/Documenti/StreamingCommunity_api-main/run.py", line 54, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Api/tv.py", line 154, in main_dw_tv
    dw_single_ep(tv_id, eps, index_ep_select, domain, token, tv_name, season_select)
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Api/tv.py", line 134, in dw_single_ep
    dw_m3u8(m3u8_url, m3u8_url_audio, m3u8_key, mp4_path)
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Util/FFmpeg/m3u8.py", line 241, in dw_m3u8
    downloader.download_and_save_ts()
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Util/FFmpeg/m3u8.py", line 198, in download_and_save_ts
    list(tqdm(executor.map(self.decrypt_and_save, range(len(self.segments)) ), total=len(self.segments), unit="bytes", unit_scale=True, unit_divisor=1024, desc="[yellow]Download"))
  File "/usr/lib/python3/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Util/FFmpeg/m3u8.py", line 171, in decrypt_and_save
    ts_response = self.make_req_single_ts_file(audio_ts_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/urlo/Documenti/StreamingCommunity_api-main/Src/Util/FFmpeg/m3u8.py", line 137, in make_req_single_ts_file
    req = requests.get(ts_url, headers={'user-agent': get_headers()}, timeout=10, allow_redirects=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='sc-u7-01.scws-content.net', port=443): Max retries exceeded with url: /hls/180/9/da/9da93c0f-ba83-46e2-891e-5c1d2aa38016/audio/ita/0403-0100.ts (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1cb82c45d0>, 'Connection to sc-u7-01.scws-content.net timed out. (connect timeout=10)')) 
```

As you see, the episode fails to download in a % among 50-68. I am using Linux,  a Ubuntu Based distro. This both happens with default and custom DNS.  Maybe you will be able to fix it.  
Thanks in advance.

**Comment by Arrowar** [comment]
Name series / ep or film ?

**Comment by UrloMythus** [comment]
I am trying to download Percy Jackson Season1  Episode 3

**Comment by Arrowar** [comment]
For me work.  

![image](https://github.com/Ghost6446/StreamingCommunity_api/assets/62809003/965aa45b-5e8b-4a40-93fc-d5ed4138c99d)

Maybe you exceed req to host='sc-u7-01.scws-content.net', try tomorrow.

But for other film \ series there is problem ?
