### ISSUE TITLE
Error ffmpeg

### ISSUE THREAD

**Issue by Anakonder98** [AstraeLabs/VibraVid#24]
dopo che installo il programma nessun problema se non questo:

  WARNING: The scripts imageio_download_bin.exe and imageio_remove_bin.exe are installed in 'C:\Users\matt9\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  
  Ne sono usciti tipo 5/6 ma non vedo che sono errori ma semplici avvisi. Dopodichè eseguo il file run.py ma ottengo queste stringhe e non so cosa dovrei fare e/o cosa mi richiede che io faccia il programma. 

Traceback (most recent call last):
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 62, in <module>
    main()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 37, in main
    initialize()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 28, in initialize
    check_ffmpeg()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\Src\Util\FFmpeg\installer.py", line 39, in check_ffmpeg
    subprocess.run(["ffmpeg", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
PS C:\Users\matt9\Downloads\StreamingCommunity_api-main>

Ho la cartella "principale" del downloader come si vede nella cartella download, può essere quello il problema?

**Comment by Arrowar** [comment]
E un problema che riguarda la tua installazione di  python, prova la 3.9

**Comment by Anakonder98** [comment]
> E un problema che riguarda la tua installazione di python, prova la 3.9

Guarda, anche con la 3.9 il problema risulta questo:

Traceback (most recent call last):
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 62, in <module>
    main()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 37, in main
    initialize()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 28, in initialize
    check_ffmpeg()
  File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\Src\Util\FFmpeg\installer.py", line 39, in check_ffmpeg
    subprocess.run(["ffmpeg", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
PS C:\Users\matt9\Downloads\StreamingCommunity_api-main>

non so perchè abbia segnato come risolto sto problema (?)
