### ISSUE TITLE
Error ffmpeg 2 [instal]

### ISSUE THREAD

**Issue by Anakonder98** [AstraeLabs/VibraVid#25]
Anche con la 3.9 il problema risulta questo:

Traceback (most recent call last):
File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 62, in
main()
File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 37, in main
initialize()
File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\run.py", line 28, in initialize
check_ffmpeg()
File "C:\Users\matt9\Downloads\StreamingCommunity_api-main\Src\Util\FFmpeg\installer.py", line 39, in check_ffmpeg
subprocess.run(["ffmpeg", "-version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
PS C:\Users\matt9\Downloads\StreamingCommunity_api-main>

Non saprei che fare :/

**Comment by Arrowar** [comment]
Penso che sia perché non hai ffmpeg in path windows

**Comment by Anakonder98** [comment]
Quindi devo solo disinstallarlo e reinstallarlo nel disco C e magari in una cartella tutta sua?

**Comment by Arrowar** [comment]
se fai ffmpeg -version nel terminale funziona o da errori ?

**Comment by Anakonder98** [comment]
Ho eseguito il comando aprendo cmd all'interno della cartella dove c'è il programma, ecco cosa mi dice:


ffmpeg : Termine 'ffmpeg' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script.
Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ ffmpeg -version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (ffmpeg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Arrowar** [comment]
Ma lo script prima ti diceva che ffmpeg è stato trovato o no ?
Segui questo tutorial https://phoenixnap.com/kb/ffmpeg-windows e dopo riprova.

**Comment by Anakonder98** [comment]
> Ma lo script prima ti diceva che ffmpeg è stato trovato o no ? Segui questo tutorial https://phoenixnap.com/kb/ffmpeg-windows e dopo riprova.

Si, lo script diceva che era installato e che funzionava.
Perfetto eseguo subito la guida, grazie

**Comment by Arrowar** [comment]
Di niente
