### ISSUE TITLE
Problema ultima versione 0.8.5

### ISSUE THREAD

**Issue by dizplayy** [AstraeLabs/VibraVid#36]
Movie select: The Walk
Quality select => 1080p
Traceback (most recent call last):
  File "d:\TORRENT\_StreamingCommunity_api\run.py", line 64, in <module>
    main()
  File "d:\TORRENT\_StreamingCommunity_api\run.py", line 51, in main
    download_film(selected_title['id'], selected_title['slug'], domain)
  File "d:\TORRENT\_StreamingCommunity_api\Src\Api\film.py", line 106, in main_dw_film
    download_m3u8(m3u8_index=m3u8_url, m3u8_audio=m3u8_url_audio, m3u8_subtitle=m3u8_url, key=m3u8_key, output_filename=mp4_path)
  File "d:\TORRENT\_StreamingCommunity_api\Src\Lib\FFmpeg\my_m3u8.py", line 451, in download_m3u8
    parse_class_m3u8.parse_data(df_make_req(m3u8_subtitle))
    ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'parse_class_m3u8' where it is not associated with a value
PS D:\TORRENT\_StreamingCommunity_api>

**Comment by Arrowar** [comment]
Risolto, ora carico la nuova versione
