### ISSUE TITLE
Crash UnicodeEncodeError

### ISSUE THREAD

**Issue by Fede14it** [AstraeLabs/VibraVid#54]
Quando provo a scaricare il 5^ episodio di WandaVision va in crash Unicode anche "What If...?" sicuramente i primi 2 episodi
----------------------------------------------------------------------------

   _____ _                            _                _____                                      _ _
  / ____| |                          (_)              / ____|                                    (_) |
 | (___ | |_ _ __ ___  __ _ _ __ ___  _ _ __   __ _  | |     ___  _ __ ___  _ __ ___  _   _ _ __  _| |_ _   _
  \___ \| __| '__/ _ \/ _` | '_ ` _ \| | '_ \ / _` | | |    / _ \| '_ ` _ \| '_ ` _ \| | | | '_ \| | __| | | |
  ____) | |_| | |  __/ (_| | | | | | | | | | | (_| | | |___| (_) | | | | | | | | | | | |_| | | | | | |_| |_| |
 |_____/ \__|_|  \___|\__,_|_| |_| |_|_|_| |_|\__, |  \_____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|_|\__|\__, |
                                               __/ |                                                     __/ |
                                              |___/                                                     |___/

Checking github version ...
=> Everything up to date
=> Last version: v0.8.8

StreamingCommunity_api was downloaded 9 times, but only 377.78% of You(!!) have starred it.
        Help the repository grow today, by leaving a star and sharing it to others online!

Checking ffmpeg ...
FFmpeg => Find

Get rules ...
Test domain => report
Rules => .report

Insert word to search in all site: : wandavision
0 -> WandaVision - tv

Total result: 1

Insert index number or [1-2] for a range of movies/tv or [1,3,5] to select discontinued movie/tv

In case of tv show you will have to choose season and episode to download

Index to download: : 0

Tv select: WandaVision

Insert season number or (*) to download all seasons or [1-2] for a range of season

Season find: 1

Insert season number: : 1
Ep: 1 => Girato davanti a un pubblico in studio
Ep: 2 => Non cambiare canale
Ep: 3 => Ora a colori
Ep: 4 => Interrompiamo questo programma
Ep: 5 => In questo episodio molto speciale…
Ep: 6 => Nuovissimo Halloween spaventacolare!
Ep: 7 => Infrangere la quarta parete
Ep: 8 => Negli episodi precedenti
Ep: 9 => The Series Finale

Insert ep number or (*) to download all ep or [1-2] for a range of ep: : [5-9]
Download ep: 5 => In questo episodio molto speciale…
Quality select => 1080p
Traceback (most recent call last):
  File "c:\Sviluppo\StreamingCommunity_api\run.py", line 93, in <module>
    main()
  File "c:\Sviluppo\StreamingCommunity_api\run.py", line 60, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "c:\Sviluppo\StreamingCommunity_api\Src\Api\tv.py", line 180, in main_dw_tv
    dw_single_ep(tv_id, eps, n_randge_ep-1, domain, token, tv_name, season_select)
  File "c:\Sviluppo\StreamingCommunity_api\Src\Api\tv.py", line 135, in dw_single_ep
    m3u8_key = get_m3u8_key_ep(json_win_video, json_win_param, tv_name, season_select, index_ep_select+1, eps[index_ep_select]['name'], token_render)       
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "c:\Sviluppo\StreamingCommunity_api\Src\Api\tv.py", line 97, in get_m3u8_key_ep
    req = requests.get('https://vixcloud.co/storage/enc.key', headers={
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connection.py", line 399, in request
    self.putheader(header, value)
  File "C:\Users\fedef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connection.py", line 313, in putheader
    super().putheader(header, *values)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1304, in putheader        
    values[i] = one_value.encode('latin-1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 162: ordinal not in range(256)

**Comment by Arrowar** [comment]
Ok se riesco oggi lo risolvo
