### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by CannotTouch** [AstraeLabs/VibraVid#56]
with [the latest version](https://github.com/Ghost6446/StreamingCommunity_api/commit/4243bb4bdf7c055a3f04edc2317e120864d8cf53) and python 3.11

Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\Src\Lib\FFmpeg\my_m3u8.py", line 320, in join
    ffmpeg.input(file_list_path, format='concat', safe=0).output(output_filename, c='copy', loglevel='quiet').run()
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StreamingCommunity_api-main\run.py", line 93, in <module>
    main()
  File "E:\StreamingCommunity_api-main\run.py", line 60, in main
    download_tv(selected_title['id'], selected_title['slug'], site_version, domain)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 193, in main_dw_tv
    dw_single_ep(tv_id, eps, int(ep['n'])-1, domain, token, tv_name, season_select)
  File "E:\StreamingCommunity_api-main\Src\Api\tv.py", line 146, in dw_single_ep
    download_m3u8(m3u8_index=m3u8_url, m3u8_audio=m3u8_url_audio, m3u8_subtitle=m3u8_playlist, key=m3u8_key, output_filename=mp4_path)
  File "E:\StreamingCommunity_api-main\Src\Lib\FFmpeg\my_m3u8.py", line 467, in download_m3u8
    M3U8_Downloader(m3u8_index, m3u8_audio, key=key, output_filename=output_filename).start()
  File "E:\StreamingCommunity_api-main\Src\Lib\FFmpeg\my_m3u8.py", line 342, in start
    video_m3u8.join(self.video_path)
  File "E:\StreamingCommunity_api-main\Src\Lib\FFmpeg\my_m3u8.py", line 321, in join
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'

**Comment by Arrowar** [comment]
Retry, what film \ episode ?

**Comment by CannotTouch** [comment]
un amore 
serie 1 
*

at the end of episode 1

[15:21:23] Download video ts                                                                             my_m3u8.py:339
Download 100% -------------------------------------------------------------  884/886  [ 0:02:03 < 0:00:01 , 8 bytes/s ]
[15:23:27] Start join all file                                                                           my_m3u8.py:318

**Comment by CannotTouch** [comment]
i have try with [5-6] instead of * and it worked correctly for both the episodes... so probably is something with the first.

**Comment by Arrowar** [comment]
Try https://github.com/Ghost6446/StreamingCommunity_api/releases/tag/v0.8.9, if there is error, retry.
