### ISSUE TITLE
Missing urllib3

### ISSUE THREAD

**Issue by jacopeste05** [AstraeLabs/VibraVid#68]
Traceback (most recent call last):
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\run.py", line 4, in <module>
    import Src.Api.page as Page
  File "C:\Users\jacop\Desktop\StreamingCommunity_api-main\Src\Api\page.py", line 8, in <module>
    import requests, sys, json
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by Fede14it** [comment]
Hai l' ultima versione del programma?
Prova ad eseguire `pip install -r requirements.txt`
