### ISSUE TITLE
update.py wipes the whole folder

### ISSUE THREAD

**Issue by Omixxx** [AstraeLabs/VibraVid#77]
When running `update.py` using `python3` in a virtual environment i get the following error:

```Traceback (most recent call last):
  File "/home/tut/projects/StreamingCommunity_api/update.py", line 102, in <module>
  File "/home/tut/projects/StreamingCommunity_api/update.py", line 100, in main_upload
  File "/home/tut/projects/StreamingCommunity_api/update.py", line 53, in download_and_extract_latest_commit
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/adapters.py", line 458, in send
  File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/adapters.py", line 261, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/certifi/cacert.pem
```
 
I'm using wezterm with the shell fish. i created the virtual environment using `venv`(`python3 -m venv .venv`) and source it `source .venv/bin/activate.fish` then ran the update via `python3 update.py` and got the error described in the stacktrace above, wiping all the files in the folder except "videos" which remained unchanged

**Comment by Arrowar** [comment]
> When running `update.py` using `python3` in a virtual environment i get the following error:
> 
> ```Traceback (most recent call last):
>   File "/home/tut/projects/StreamingCommunity_api/update.py", line 102, in <module>
>   File "/home/tut/projects/StreamingCommunity_api/update.py", line 100, in main_upload
>   File "/home/tut/projects/StreamingCommunity_api/update.py", line 53, in download_and_extract_latest_commit
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/adapters.py", line 458, in send
>   File "/home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/requests/adapters.py", line 261, in cert_verify
> OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /home/tut/projects/StreamingCommunity_api/.venv/lib/python3.11/site-packages/certifi/cacert.pem
> ```
>  
> I'm using wezterm with the shell fish. i created the virtual environment using `venv`(`python3 -m venv .venv`) and source it `source .venv/bin/activate.fish` then ran the update via `python3 update.py` and got the error described in the stacktrace above, wiping all the files in the folder except "videos" which remained unchanged

You need to create certificate, this is not a typically error using win. https://stackoverflow.com/questions/39356413/how-to-add-a-custom-ca-root-certificate-to-the-ca-store-used-by-pip-in-windows
