### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#84]
aggiornandolo e provandolo oggi mi da questo errore:

C:\Users\user\Downloads\StreamingCommunity_api-main>python run.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\StreamingCommunity_api-main\run.py", line 4, in <module>
    import Src.Api.page as Page
  File "C:\Users\user\Downloads\StreamingCommunity_api-main\Src\Api\page.py", line 4, in <module>
    from Src.Util.headers import get_headers
  File "C:\Users\user\Downloads\StreamingCommunity_api-main\Src\Util\headers.py", line 4, in <module>
    import fake_useragent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by Arrowar** [comment]
https://pypi.org/project/fake-useragent/
