### ISSUE TITLE
Error ffmpeg

### ISSUE THREAD

**Issue by ludogemma** [AstraeLabs/VibraVid#9]
subito dopo il download mi da questo errore:

Movie select: Saltburn
Find: 1974 ts file to download
Download 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 K [ 0:02:12 < 0:00:00 , 16 bytes/s ]
Start join all file
Traceback (most recent call last):
  File "C:\Users\Sergio\Desktop\StreamingCommunity\run.py", line 42, in <module>
    main()
  File "C:\Users\Sergio\Desktop\StreamingCommunity\run.py", line 33, in main
    download_film(db_title[index_select]['id'], db_title[index_select]['name'].replace(" ", "+"), domain)
  File "C:\Users\Sergio\Desktop\StreamingCommunity\Stream\api\film.py", line 55, in main_dw_film
    dw_m3u8(m3u8_url, m3u8_key, path_film)
  File "C:\Users\Sergio\Desktop\StreamingCommunity\Stream\util\m3u8.py", line 133, in dw_m3u8
    downloader.join_ts_files()
  File "C:\Users\Sergio\Desktop\StreamingCommunity\Stream\util\m3u8.py", line 116, in join_ts_files
    ffmpeg.input(file_list_path, format='concat', safe=0).output(self.output_filename, c="copy", loglevel="quiet").run()
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Sergio\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

ho provato sia con la versione 0.61 che 0.70 identico errore 

Grazie

**Comment by Arrowar** [comment]
Hai aggiunto ffmpeg al path di windows ?

**Comment by ludogemma** [comment]
Grazie adesso funziona :)

**Comment by Arrowar** [comment]
Perfetto
